# fly.toml app configuration file generated for dca5 on 2026-07-28T09:12:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dca5'
primary_region = 'iod'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[mounts]]
  source = 'dca5_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
